language: node_js
node_js:
    - node

before_install:
    - cd client
    - npm install -g yarn

install:
    - yarn install

script:
    - yarn build
    #- yarn test

deploy:
  provider: azure_web_apps
  site: jobapplicationtracker
  on:
    branch: master
  edge: true # opt in to dpl v2